### ISSUE TITLE
build issues for X86 Linux 

### ISSUE THREAD

**Issue by BourneYin** [elucideye/acf#103]
I try to build the libs for x86 linux with command: polly.py --toolchain gcc  --install --verbose,
But I can't get the tools needed for check_ci_tags corresponding to Toolchain-ID.
Some info as follows:
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] HUNTER_TOOLCHAIN_ID_PATH: /home/bourne/.hunter/_Base/e7fe3f0/427fd52
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] HUNTER_CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] HUNTER_BUILD_SHARED_LIBS:
-- [hunter] [ Hunter-ID: e7fe3f0 | Toolchain-ID: 427fd52 | Config-ID: a0274a8 ]
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] load: /home/bourne/.hunter/_Base/Download/Hunter/0.22.8/e7fe3f0/Unpacked/cmake/projects/check_ci_tag/hunter.cmake
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] check_ci_tag versions available: [1.0.0]
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Package 'check_ci_tag' CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Package 'check_ci_tag' is cacheable: YES
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Install to: /home/bourne/.hunter/_Base/e7fe3f0/427fd52/a0274a8/Install
-- [hunter] CHECK_CI_TAG_ROOT: /home/bourne/.hunter/_Base/e7fe3f0/427fd52/a0274a8/Install (ver.: 1.0.0)
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Locking directory: /home/bourne/.hunter/_Base/Download/check_ci_tag/1.0.0/f220960
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Lock done
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Already locked: /home/bourne/.hunter/_Base/Download/check_ci_tag/1.0.0/f220960
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Locking directory: /home/bourne/.hunter/_Base/e7fe3f0/427fd52/a0274a8
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Lock done
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Locking directory: /home/bourne/.hunter/_Base/Cache
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Lock done
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Using CMake variable HUNTER_PASSWORDS_PATH
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] Downloading DONE metafile (try #0 of 10):
-- [hunter *** DEBUG *** 2019-04-19T18:18:41]   https://raw.githubusercontent.com/elucideye/hunter-cache/master/427fd52/check_ci_tag/1.0.0/f220960/da39a3e/a49b0e5/da39a3e/basic-deps.DONE
-- [hunter *** DEBUG *** 2019-04-19T18:18:41]   -> /home/bourne/.hunter/_Base/Cache/meta/427fd52/check_ci_tag/1.0.0/f220960/da39a3e/a49b05/da39a3e/basic-deps.DONE
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
I look forward to your suggestions and tips.

**Comment by ruslo** [comment]
> -- [hunter *** DEBUG *** 2019-04-19T18:18:41] https://raw.githubusercontent.com/elucideye/hunter-cache/master/427fd52/check_ci_tag/1.0.0/f220960/da39a3e/a49b0e5/da39a3e/basic-deps.DONE
-- [hunter *** DEBUG *** 2019-04-19T18:18:41] -> /home/bourne/.hunter/_Base/Cache/meta/427fd52/check_ci_tag/1.0.0/f220960/da39a3e/a49b05/da39a3e/basic-deps.DONE

It's a cache. If there is no such file in the cache, the build from source will be used; in general, it's not an error.

**Comment by BourneYin** [comment]
> > -- [hunter *** DEBUG *** 2019-04-19T18:18:41] https://raw.githubusercontent.com/elucideye/hunter-cache/master/427fd52/check_ci_tag/1.0.0/f220960/da39a3e/a49b0e5/da39a3e/basic-deps.DONE
> > -- [hunter *** DEBUG *** 2019-04-19T18:18:41] -> /home/bourne/.hunter/_Base/Cache/meta/427fd52/check_ci_tag/1.0.0/f220960/da39a3e/a49b05/da39a3e/basic-deps.DONE
> 
> It's a cache. If there is no such file in the cache, the build from source will be used; in general, it's not an error.

Thanks,  
In fact, I want to ask, why does the following link file not exist, because it has been removed?
Https://raw.githubusercontent.com/elucideye/hunter-cache/master/427fd52/check_ci_tag/1.0.0/f220960/da39a3e/a49b0e5/da39a3e/basic-deps.DONE

**Comment by ruslo** [comment]
> why does the following link file not exist, because it has been removed?

There are no cache binaries uploaded for this configuration.

URL constructed by Hunter from local configuration and mean "REQUEST: Toolchain-ID: 427fd52, check_ci_tag 1.0.0 sources f220960, etc". Response from server is 404 - there is no such entry uploaded => you can build from sources.

**Comment by BourneYin** [comment]
> > why does the following link file not exist, because it has been removed?
> 
> There are no cache binaries uploaded for this configuration.
> 
> URL constructed by Hunter from local configuration and mean "REQUEST: Toolchain-ID: 427fd52, check_ci_tag 1.0.0 sources f220960, etc". Response from server is 404 - there is no such entry uploaded => you can build from sources.

Thank you very much. It seems to me that the reason for the problem has been found. This 'fake issue ' 
 can be closed.
