### ISSUE TITLE
Ubuntu 18.04 w/ gcc-5-pic-hid-sections-lto

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/acf#107]
Migrated from (1) https://github.com/elucideye/acf/issues/102#issuecomment-487247357

Runtime error:

```
Exception: glfwCreateWindow(): Assertion 'm_context' failed in file '/home/bourne/.hunter/_Base/6421d63/1247837/7868414/Build/aglet/Source/lib/aglet/GLFWContext.cpp' line 94
```

**Comment by headupinclouds** [comment]
> Assertion 'm_context' failed

@BourneYin I think error is common in glfw when there is some kind of problem with the GPU.  Do you have a GPU?  There are probably a lot of reasons this could fail.  For example, if you are working remotely attempting headless rendering.  Maybe some of this is relevant https://github.com/intel-isl/Open3D/issues/17.  You can also request a context via EGL, which might help.  I'm trying Ubuntu 18.04 now.

**Comment by headupinclouds** [comment]
# Install system OpengL, EGL,  OpenGL ES 2.0
```
sudo apt-get install libglfw3-dev libgles2-mesa-dev 
```

# Update the repo

> Requires https://github.com/elucideye/acf/pull/110

```
git pull
git submodule update --init --recursive
```

# Run tests:

https://gist.github.com/headupinclouds/4bb7928cdd6b77955f92524e47d2af40

```
bash  test_acf.sh
```

```
for i in gcc-5-pic-hid-sections_*.txt; do echo $i; cat $i; gnome-open ${i} done
```

### gcc-5-pic-hid-sections_es2OFF_es3OFF_cpu.txt
[15:58:48.388 | thread:27335 | acf-detect | info]: 1/1 n-EYES-628x314.jpg = 2; score = 141.611

![n-EYES-628x314_objects](https://user-images.githubusercontent.com/554720/56869485-71ce4100-69cf-11e9-8051-c41f8e939d95.jpg)

### gcc-5-pic-hid-sections_es2OFF_es3OFF_gpu.txt
[15:58:48.466 | thread:27338 | acf-detect | info]: 1/1 n-EYES-628x314.jpg = 2; score = 147.731

![n-EYES-628x314_objects](https://user-images.githubusercontent.com/554720/56869491-8579a780-69cf-11e9-849b-ec80511f2f1e.jpg)

### gcc-5-pic-hid-sections_es2ON_es3OFF_cpu.txt
[15:57:13.050 | thread:26368 | acf-detect | info]: 1/1 n-EYES-628x314.jpg = 2; score = 141.611


![n-EYES-628x314_objects](https://user-images.githubusercontent.com/554720/56869497-8d394c00-69cf-11e9-8a23-0559aa716395.jpg)


### gcc-5-pic-hid-sections_es2ON_es3OFF_gpu.txt
[15:57:13.128 | thread:26371 | acf-detect | info]: 1/1 n-EYES-628x314.jpg = 2; score = 149.846


![n-EYES-628x314_objects](https://user-images.githubusercontent.com/554720/56869499-92969680-69cf-11e9-8ef2-1a77ebcffb45.jpg)

**Comment by BourneYin** [comment]
> > Assertion 'm_context' failed
> 
> @BourneYin I think error is common in glfw when there is some kind of problem with the GPU. Do you have a GPU? There are probably a lot of reasons this could fail. For example, if you are working remotely attempting headless rendering. Maybe some of this is relevant [intel-isl/Open3D#17](https://github.com/intel-isl/Open3D/issues/17). You can also request a context via EGL, which might help. I'm trying Ubuntu 18.04 now.


Thank you very much.　I did use Intel graphics cards before. Regretfully，I switched to AMD platform and still had the same problem.

I'll try you #110 request.
Thank you again for your help！！

**Comment by BourneYin** [comment]
#110　works fine on x86 ubuntu18.04! Great jobs!!

**Comment by headupinclouds** [comment]
Merged.
