### ISSUE TITLE
cpb file

### ISSUE THREAD

**Issue by xingwangsfu** [elucideye/acf#19]
Hi,

Thanks for your work. I'm trying to port the pedestrian detector in Piotr's Matlab Toolbox to this package. However, I have no idea on how to generate cpb file from the pretrained model. Would you mind sharing the steps to generate the .cpb file?

Thanks,
Xing

**Comment by xingwangsfu** [comment]
It seems like there is a mat2cpb function that can do this for me.

**Comment by headupinclouds** [comment]
Actually, you should be able to load the `*.mat` files directly.  The `CMake` option that enables the `cvmatio` lib is here: 

https://github.com/elucideye/acf/blob/da09a7a44ffc3cf94cee22b55fdb20375ca561fc/CMakeLists.txt#L96

The `mat2cpb` application simply deserializes a `*.mat` model and (re)serializes using a cereal archive.    I've only loaded models that I have trained by myself form the toolbox.  Let me know if you aren't able to load a toolbox model for some reason.  I'd be happy to take a look at any failures.
