### ISSUE TITLE
OpenCV error on Raspberry Pi 3

### ISSUE THREAD

**Issue by xingwangsfu** [elucideye/acf#20]
Hi,

I installed the package on raspberry pi 3 with TOOLCHAIN=linux-gcc-armf-neon-vfpv4. There is no error during complilation. I can succefully install it.

However, when I tried to run it with "./acf-detect --input=lene512color.png --output=/tmp/ --model=drishti_face_gray_80x80.cpb --nms --annotate --calibration=0.00001", I got the following OpenCV error 
"OpenCV Error: One of arguments' values is out of range (The total matrix size does not fit to "size_t" type) in setSize, file /home/ubuntu/.hunter/_Base/57d0748/f2f4970/0352f92/Build/OpenCV/Source/modules/core/src/matrix.cpp, line 309 Exception: /home/ubuntu/.hunter/_Base/57d0748/f2f4970/0352f92/Build/OpenCV/Source/modules/core/src/matrix.cpp:309: error: (-211) The total matrix size does not fit to "size_t" type in function setSize".

I didn't do any change to the code. I thought the image size might be too large for Pi since the memory of Pi is only 1GB. So I also tried to use Lena256. Unfortunately, I had the same error. 

Have you ever met this problem before?

Thanks,
Xing

**Comment by headupinclouds** [comment]
I haven't tried it on Raspberry Pi yet, but I would be curious to know where it is failing.  

"lene512color.png" should be "lena512color.png".  Was that a typo?

Can you try to isolate the issue via gdb or logging?  If you are using `polly.py` you can specify `--config=Debug` for a debug build.  I haven't seen this issue before, so without additional context it is hard for me to help.

**Comment by headupinclouds** [comment]
TODO: QEMU Raspberry Pi Emulator for testing https://github.com/hunter-packages/gauze/issues/4

**Comment by xingwangsfu** [comment]
The "lene512color.png" was a type. It has nothing to do with the error. Thanks for your suggestion. I'll try to use gdb to find where the error happened.

**Comment by headupinclouds** [comment]
Thanks for the update, and thanks for testing on Raspberry Pi.  I'd love to confirm end-to-end behavior is OK on this platform.  It really should work.  I did purchase a Raspberry Pi for tinkering, but it is still in the box.  I will try to set it up.

**Comment by xingwangsfu** [comment]
Ok, this is an update of this issue.
I digged into the code and found the problem happened where the model .cpb file was loaded. For some reason, the provided face.cpb file can not be loaded. Then, I downloaded some pretrained mat files from the toolbox and loaded these mat files instead of cpb files. Everything is working perfectly.

**Comment by headupinclouds** [comment]
I'm glad it is working.  Can you run the exact same build command but with a toolchain for your desktop system and then try running the command line application with the same arguments?  I guess it is possible there is some problem with the cereal portable binary archives on Raspberry Pi devices.  If the same commands work fine for you on a "desktop" device that would be a useful data point.

**Comment by headupinclouds** [comment]
@xingwangsfu : I was able to reproduce the issue on a Raspberry Pi 3 B.  The problem was introduced with the `wget` command I provided in the README.  The github URL for downloading binary files should use `raw` and not `blob`.  If you run wget again with this syntax it should work fine.  Sorry for the confusion:

new/correct:
```
wget https://github.com/elucideye/drishti-assets/raw/master/drishti_face_gray_80x80.cpb
```

old/broken:
```
wget https://github.com/elucideye/drishti-assets/raw/master/drishti_face_gray_80x80.cpb
```
