### ISSUE TITLE
Failed to load AcfCaltech+Detector.mat

### ISSUE THREAD

**Issue by xingwangsfu** [elucideye/acf#22]
Hi David,
As I said before, I could successfully load AcfInriaDetector.mat and perform pedestrian detection. However, when I tried to load AcfCaltech+Detector.mat without making any change of the code, I got the following error 
"*** Error in './acf-detect': corrupted size vs. prev_size: 0x01a91098 ***"
It seems to me the code is using memory which was not allocated to it.

After further investigation, I found the error happed here
```
 int Detector::operator()(const MatP& IpTranspose, std::vector<cv::Rect>& objects, std::vector<double>* scores)
{
    // Create features:
    Pyramid P;
    chnsPyramid(IpTranspose, &opts.pPyramid.get(), P, true);
```
For AcfInriaDetector.mat, the window size is 100x41 while it is 50x20 for AcfCaltech+Detector.mat. These parameters are loaded automatically from .mat files.

Do I need to make any changes to the code if I want to load AcfCaltech+Detector.mat?

**Comment by headupinclouds** [comment]
This relates to #20 .  I was able to reproduce this one as well on Raspberry Pi.  I *think* the `*.mat` format (or possibly cvmatio) has some problem loading models from a 64 bit host on a 32 bit system.  If ran `acf-mat2cpb`, now that the PI + `*.cpb` issue has been resolved, and that seems to load the model okay, but it turns up a `depth=2` optimization assumption/assertion I had made in the original project.  I will fix that one for general purpose use. 

Convert using this command on the host machine:
```
./bin/acf-mat2cpb  --input=share/AcfCaltech+Detector.mat --output=share/AcfCaltech+Detector.cpb
```

**Comment by headupinclouds** [comment]
I've pushed https://github.com/elucideye/acf/pull/23 for now.  This removes the legacy `depth==2` assertion and enables the overloaded`depth==0` variable depth tree evaluation.  I did test `AcfCaltech+Detector.mat` with an random image with pedestrians and the code runs but I didn't see any detections.  It might take a little more digging.  If you have a recommended test image for that classifier with known output you can post it here for testing and I can take a look.  I can look more this weekend.

**Comment by headupinclouds** [comment]
@xingwangsfu : The variable tree depth evaluation needed by `AcfCaltech+Detector.mat` is fixed in  https://github.com/elucideye/acf/pull/25 .  I've compared this with the matlab code on a caltech sample frame (V002 # 1700).

![v002_1700_objects](https://user-images.githubusercontent.com/554720/32379292-83df6190-c083-11e7-8e2c-5cb8921d845d.jpg)

The PR is currently being tested and should be merged soon.

**Comment by xingwangsfu** [comment]
@headupinclouds  Cool. Thanks a lot.
