### ISSUE TITLE
Calculating scales with nOctUp != 0 causes issues

### ISSUE THREAD

**Issue by JN-Jones** [elucideye/acf#67]
Similar to #62: If `nOctUp` is not `0` the scaling doesn't work. This is caused by `double s = std::pow(2.0, -double(i) / double(nPerOct + nOctUp));` which adds `nOctUp` to `nPerOct` before the division while the matlab code does `scales = 2.^(-(0:nScales-1)/nPerOct+nOctUp);` which adds it after the divion. Simple fix would be to cast both variables seperatly: `double s = std::pow(2.0, -double(i) / double(nPerOct) + double(nOctUp));`

**Comment by headupinclouds** [comment]
Thanks again.  I'll send a fix shortly.

**Comment by headupinclouds** [comment]
Merged.
