### ISSUE TITLE
gradient hist channels are swapped

### ISSUE THREAD

**Issue by JN-Jones** [elucideye/acf#72]
Hi, it seems that the (by default 6) histogram channels are swapped compared to the matlab code. I'm not yet sure what exactly causes this or whether this even counts as an issue but at least for #71 this needs to be addressed in some way. If using the default options in gray color space which results in 8 channels (one color, one magnitude and the six hist channels the following channels are swapped:
* 2 and 5
* 3 and 4
* 6 and 7

Also the calculated values are a bit off compared to the matlab code though I'm not yet sure whether that's caused by the library or by OpenCV (even calculating the pyramid in matlab and importing the images with OpenCV causes a little change in the values). I'll keep searching^^

**Comment by headupinclouds** [comment]
I'll have some time to look tomorrow.  My guess is that it stems from workarounds for the column major storage assumptions of the SIMD code.

**Comment by headupinclouds** [comment]
Matlab reference (TODO: match c++ orientation) ...

![dodecagon](https://user-images.githubusercontent.com/554720/40271519-3fc29598-5b6c-11e8-9396-b737cd88e77f.png)

```
I=imread('dodecagon.png');
pPyramid=chnsPyramid();
P2=chnsPyramid(I,pPyramid);
prm = struct('perRow',10);
montage2(P2.data{2},prm)
```

<img width="743" alt="dodecagon_matlab" src="https://user-images.githubusercontent.com/554720/40271530-5bb95cd2-5b6c-11e8-90a3-9e07732c81a4.png">

**Comment by headupinclouds** [comment]
I believe the histogram orientations are correct as long as the input image is transposed.  I'm going to close this issue in favor of the more general pixel level comparison tests proposed in #71.  (I do see some minor differences in the top animated cpp vs Matlab GIF in the above issue that are worth understanding.)

**Comment by headupinclouds** [comment]
Added documentation issue https://github.com/elucideye/acf/issues/74 to clarify pre-conditions for lib users.

**Comment by JN-Jones** [comment]
Transposing seems to have done the trick, thanks.

**Comment by headupinclouds** [comment]
That requirement can probably be removed at some point with some effort.
